project:
  output-dir: _revealjs
  render:
    - 01_command_shells.qmd
    - 02_python_environments.qmd
    - 03_git_github.qmd
    - 04_scc.qmd
    - 06_scc_cont.qmd

format:
  revealjs:
    footer: "DS549 -- Gardos"
    scrollable: true
    slide-number: c/t
    show-slide-number: all
    chalkboard: true
    smaller: true
    html-math-method: mathjax
    echo: true
    code-fold: false
